project: "kooba/brigade-tutorial-config"
repository: "github.com/kooba/brigade-tutorial-config"
cloneURL: "https://github.com/kooba/brigade-tutorial-config"
workerCommand: node_modules/.bin/tsc brigade.ts; yarn start
